#!/usr/bin/env bash

# this script list items in current dir and ask to delete every item or not.

for item in * .*; do 
  # skip . and .. 
  [[ "$item" == "." ]] || [[ "$item" == ".." ]] && continue 

  # handles non existent items 
  [[ ! -e "$item" ]] && continue

  while true; do
    read -rp "Delete "$item" ? [y/n/q]: " answer 

    case "$answer" in 
      [yY]) 
        mv "$item" ~/.local/share/Trash
        echo "$item deleted"
        echo "========================================"
        break
        ;;
      [nN]) 
        break 
        ;; 
      [qQ]) 
        echo "exiting..." && exit 0 
        ;;
      *) 
        echo "Invalid input, please use y/n/q only" 
        ;;
    esac
  done 
done
